sed -i '/std::vector<flecs::entity> resources_module_t::list_resources() const {/d' spectre/source/modules/resources/resources_module.cpp || true

sed -i '/void resources_module_t::import_configuration/i \
std::vector<flecs::entity> resources_module_t::list_resources() const {\n    std::vector<flecs::entity> list;\n    m_resources_root.children([&](flecs::entity e) {\n        list.push_back(e);\n    });\n    return list;\n}\n\nstd::vector<flecs::entity> resources_module_t::list_resource_loaders() const {\n    std::vector<flecs::entity> list;\n    m_loaders_root.children([&](flecs::entity e) {\n        list.push_back(e);\n    });\n    return list;\n}\n' spectre/source/modules/resources/resources_module.cpp

sed -i '/ecs_entity_t (\*find_resource)(ecs_world_t\* world, const char\* name);/i \    ecs_entity_t* (*list_resources)(ecs_world_t* world, size_t* count);\n    ecs_entity_t* (*list_resource_loaders)(ecs_world_t* world, size_t* count);' spectre/include/spectre/services/resources_service.h

sed -i '/ecs_entity_t spectre_resources_find_resource/i \SANDBOX_API\necs_entity_t* spectre_resources_list_resources(ecs_world_t* world, size_t* count);\nSANDBOX_API\necs_entity_t* spectre_resources_list_resource_loaders(ecs_world_t* world, size_t* count);\n' spectre/include/spectre/services/resources_service.h

sed -i '/static ecs_entity_t find_resource(const flecs::world& entity_world, const char\* name);/i \    static std::vector<flecs::entity> list_resources(const flecs::world& entity_world);\n    static std::vector<flecs::entity> list_resource_loaders(const flecs::world& entity_world);' spectre/include/spectre/sdk/resources.hpp

sed -i '/\.is_resource = resources_is_resource,/a \    .list_resources = resources_list_resources,\n    .list_resource_loaders = resources_list_resource_loaders,' spectre/source/modules/resources/resources_service.cpp

sed -i '/static ecs_entity_t resources_find_resource(ecs_world_t\* entity_world, const char\* name);/i \
static ecs_entity_t* resources_list_resources(ecs_world_t* entity_world, size_t* count);\nstatic ecs_entity_t* resources_list_resource_loaders(ecs_world_t* entity_world, size_t* count);\n' spectre/source/modules/resources/resources_service.cpp

sed -i '/static ecs_entity_t resources_find_resource(ecs_world_t\* entity_world, const char\* name) {/i \
static ecs_entity_t* resources_list_resources(ecs_world_t* entity_world, size_t* count) {\n    static std::vector<ecs_entity_t> result;\n    result.clear();\n    *count = 0;\n    if (!entity_world) return nullptr;\n    flecs::world flecs_world(entity_world);\n    auto* module = flecs_world.lookup("spectre::modules::resources_module_t").is_valid() ? flecs_world.try_get_mut<spectre::modules::resources_module_t>() : nullptr;\n    if (module) {\n        auto entities = module->list_resources();\n        for (auto& e : entities) result.push_back(e.id());\n    }\n    *count = result.size();\n    return result.empty() ? nullptr : result.data();\n}\n\nstatic ecs_entity_t* resources_list_resource_loaders(ecs_world_t* entity_world, size_t* count) {\n    static std::vector<ecs_entity_t> result;\n    result.clear();\n    *count = 0;\n    if (!entity_world) return nullptr;\n    flecs::world flecs_world(entity_world);\n    auto* module = flecs_world.lookup("spectre::modules::resources_module_t").is_valid() ? flecs_world.try_get_mut<spectre::modules::resources_module_t>() : nullptr;\n    if (module) {\n        auto entities = module->list_resource_loaders();\n        for (auto& e : entities) result.push_back(e.id());\n    }\n    *count = result.size();\n    return result.empty() ? nullptr : result.data();\n}\n\necs_entity_t* spectre_resources_list_resources(ecs_world_t* world, size_t* count) {\n#ifdef __cplusplus\n    flecs::world flecs_world(world);\n    const spectre_resources_service_t* service = flecs_world.try_get<spectre_resources_service_t>();\n#else\n    const spectre_resources_service_t* service = (const spectre_resources_service_t*)ecs_get(world, ecs_id(spectre_resources_service_t));\n#endif\n    if (service && service->api && service->api->list_resources) {\n        return service->api->list_resources(world, count);\n    }\n    *count = 0;\n    return nullptr;\n}\n\necs_entity_t* spectre_resources_list_resource_loaders(ecs_world_t* world, size_t* count) {\n#ifdef __cplusplus\n    flecs::world flecs_world(world);\n    const spectre_resources_service_t* service = flecs_world.try_get<spectre_resources_service_t>();\n#else\n    const spectre_resources_service_t* service = (const spectre_resources_service_t*)ecs_get(world, ecs_id(spectre_resources_service_t));\n#endif\n    if (service && service->api && service->api->list_resource_loaders) {\n        return service->api->list_resource_loaders(world, count);\n    }\n    *count = 0;\n    return nullptr;\n}\n' spectre/source/modules/resources/resources_service.cpp

sed -i '/void resources::import_configuration(const flecs::world& entity_world, const char\* path) {/i \
std::vector<flecs::entity> resources::list_resources(const flecs::world& entity_world) {\n    size_t count = 0;\n    ecs_entity_t* entities = spectre_resources_list_resources(entity_world.c_ptr(), &count);\n    std::vector<flecs::entity> list;\n    if (entities && count > 0) {\n        list.reserve(count);\n        for (size_t i = 0; i < count; ++i) {\n            list.push_back(entity_world.entity(entities[i]));\n        }\n    }\n    return list;\n}\n\nstd::vector<flecs::entity> resources::list_resource_loaders(const flecs::world& entity_world) {\n    size_t count = 0;\n    ecs_entity_t* entities = spectre_resources_list_resource_loaders(entity_world.c_ptr(), &count);\n    std::vector<flecs::entity> list;\n    if (entities && count > 0) {\n        list.reserve(count);\n        for (size_t i = 0; i < count; ++i) {\n            list.push_back(entity_world.entity(entities[i]));\n        }\n    }\n    return list;\n}\n' spectre/source/modules/resources/resources_service.cpp

sed -i 's/void list_resources() const;/std::vector<flecs::entity> list_resources() const;/g' spectre/source/modules/resources/resources_module.h
sed -i 's/void list_resource_loaders() const;/std::vector<flecs::entity> list_resource_loaders() const;/g' spectre/source/modules/resources/resources_module.h

